package dev.yasan.para.string.lorem

import androidx.compose.ui.tooling.preview.PreviewParameterProvider

class ParaStringLoremParagraphMedium : PreviewParameterProvider<String> {
    override val values: Sequence<String> = sequenceOf(
        "Lorem ipsum dolor sit amet. Qui sint illo et pariatur sapiente aut molestiae unde. Sed totam sequi est tenetur nesciunt eos totam possimus  similique asperiores est deserunt molestias aut quia voluptatem. Et repellendus quidem id sint quidem ut iusto accusantium ad molestiae nisi ad facilis internos et cupiditate officia. Ex repellendus quis et fugiat eius  labore aliquam sed molestiae quasi id quaerat voluptatem et laudantium molestiae. Est Quis amet cum deserunt veniam est iusto debitis sit quos assumenda et voluptatem culpa id nisi earum? Id magni voluptatem qui internos ipsam in optio quisquam ut perferendis sequi non nisi repellendus. Et magni magnam non quas fuga qui pariatur quos non dolor velit non enim eligendi et quod rerum.",
        "Lorem ipsum dolor sit amet. Et voluptatem illo ut praesentium autem ut modi pariatur sed molestiae expedita sed placeat nisi eum esse asperiores ut commodi quod. Ut eligendi reprehenderit a odit ipsa in debitis fugiat vel delectus similique et itaque distinctio! Aut autem iste aut quas enim quo quam praesentium qui odit quas. Rem voluptatem deserunt aut nulla error in autem minima sit nisi cupiditate. Aut velit quaerat ut Quis dolor sit optio eius non illum nihil eum fugit aperiam. Eum vero molestias qui velit officia eum dolorem illum ut voluptas tenetur id adipisci velit. Cum neque adipisci ut sint minima in rerum modi id quas natus quo dolorem tempora!",
        "Lorem ipsum dolor sit amet. Ex tempora soluta aut nihil quia nam porro eveniet sed voluptatum eaque ut veniam fuga sed sunt repellendus rem nihil velit. Ut ipsam expedita id illo eligendi ut facilis illum. Est velit suscipit qui  deserunt et perspiciatis libero aut suscipit maxime. Eum sapiente cupiditate rem earum dicta hic inventore earum. Sed aspernatur officia in esse consequatur  laborum consequuntur qui ipsam voluptas? Et similique dignissimos id doloremque saepe aut sunt fugiat. Et iusto animi 33 reiciendis aperiam aut impedit quidem qui quasi consectetur!",
        "Lorem ipsum dolor sit amet. Qui doloribus dolor quo rerum deleniti  consequuntur quas id consectetur minus non saepe obcaecati cum autem beatae nam ipsum consequatur. Sit adipisci vero et doloribus necessitatibus et quisquam cupiditate vel magni corrupti est assumenda sunt! Vel consectetur fuga est atque quas quo placeat cupiditate sit magni aliquid et sequi deleniti. Non voluptas mollitia aut dignissimos rerum nam perferendis culpa qui rerum autem id adipisci nihil. Eos aspernatur sunt qui laudantium quisquam rem perferendis magnam  adipisci officia et magnam enim vel voluptas quisquam. Qui iste nobis id voluptatem reiciendis vel sapiente voluptates ut voluptate Quis. Non aspernatur tenetur ad culpa rerum eum enim doloremque sit quis soluta a quidem quod.",
        "Lorem ipsum dolor sit amet. Sit consequatur dolores aut facilis excepturi aut blanditiis similique aut mollitia delectus non praesentium quam eum ipsam fugiat. Id galisum saepe a molestias molestiae et fugiat culpa qui temporibus adipisci est adipisci omnis et galisum iusto. At error veniam qui laudantium quisquam qui ducimus fugiat non praesentium perspiciatis. Sit corporis nobis eum eveniet quisquam et autem consequatur id consequatur libero aut dolorem nisi sit neque dolor. Ab sunt nobis non adipisci reprehenderit ea pariatur aliquid est galisum dolor et vero quae aut temporibus totam. Aut ducimus ipsam id quam nihil eos fuga facere. Et voluptatibus dolor cum aspernatur sint et beatae iure qui tempore architecto est officiis vero.",
        "Lorem ipsum dolor sit amet. At quos repellat ut mollitia officia aut doloremque commodi id aspernatur veniam. Et sapiente cupiditate sed galisum unde nam odio repellendus. Aut beatae  aut culpa voluptas 33 explicabo voluptatem hic eius galisum et odit sint et reprehenderit omnis. Et pariatur soluta qui repudiandae consequatur est temporibus omnis sit culpa explicabo in dolor voluptate qui nostrum deleniti est officiis ullam. Qui iusto dolorem et iste optio et enim dolores est unde possimus sed fugiat neque et aspernatur nesciunt. Et accusamus voluptas aut reiciendis dolores sit molestiae voluptas. Est assumenda nulla eum fugit fuga est animi facilis eos facere ullam quo autem dolores. Ut optio fugiat id blanditiis possimus quo voluptatem ducimus qui odit provident a ipsam cumque. Et rerum sint et ipsam necessitatibus et suscipit amet sed ducimus omnis et eius odit.",
        "Lorem ipsum dolor sit amet. A veniam aperiam qui enim maiores qui nobis velit ut dolores nesciunt! Qui similique porro est delectus molestias et aperiam incidunt aut delectus culpa ut velit fuga et nesciunt omnis et velit magnam? Aut accusamus explicabo ut nobis dolorum et nulla itaque et eveniet minima est labore nihil qui nihil adipisci qui omnis ipsam. Eos illo ullam et unde deleniti et aspernatur minus? Sit blanditiis velit ea suscipit omnis in laborum similique hic ipsam quia et cumque voluptatem et dolorum nisi! Vel quae enim est iste similique cum maiores eveniet rem officiis dolores ut voluptatem totam ut galisum voluptatem sed nostrum vitae. Iure voluptatem eum consequatur unde At nemo tenetur ad molestiae inventore?",
        "Lorem ipsum dolor sit amet. Ut voluptatem voluptatem ea voluptas aperiam eum nostrum voluptates ut Quis porro ut voluptatem ducimus ea iure perferendis. Ut dolor nesciunt eos reprehenderit voluptatem et laboriosam ullam et doloribus soluta! In voluptatem autem qui optio laborum nam nobis placeat et sint recusandae? Ab sunt praesentium et  suscipit et facere dolorem quo odit omnis non molestias repudiandae. Qui quaerat assumenda qui atque eius ut voluptatem obcaecati et magnam quia et quam cupiditate 33 saepe tempora ex blanditiis veniam. Et iure laboriosam sed aliquid ratione nam beatae odit et voluptatem corporis. Sed placeat pariatur ab autem veniam sit veniam deleniti et illum rerum qui quas illum nam maxime galisum est consectetur quibusdam.",
        "Lorem ipsum dolor sit amet. Cum quis dolorum ut mollitia rerum et omnis fugiat hic enim debitis non quae earum! Et enim velit est molestiae sunt sed officiis veritatis! Aut animi maxime et quia voluptatem est natus nostrum non fugit enim quo consequatur dolorem et suscipit magnam. 33 adipisci suscipit sit unde veniam eos sint voluptas et aspernatur velit! Eum sunt neque 33 culpa excepturi sed ipsa iusto hic autem cupiditate. Est repudiandae galisum ad suscipit dolores ut tempore quaerat? Quo saepe aperiam ab fuga odio 33 doloremque dolor ea tempore velit est doloribus modi eos labore quia.",
        "Lorem ipsum dolor sit amet. Nam consequatur incidunt ut repudiandae asperiores et porro voluptas. Sed blanditiis odit sed amet explicabo cum quaerat saepe sit autem illum ea possimus corrupti. Ab quam saepe sed quidem quia non neque aspernatur est quia mollitia sed sint voluptatibus vel optio assumenda est blanditiis quia. Et dolores sunt et sequi voluptas et corrupti eveniet? Vel velit culpa aut iusto quasi est sint voluptatem et voluptatem ratione. Sed dicta quam est voluptatem quia aut sequi reprehenderit aut odit alias cum consequatur voluptates non voluptatibus accusantium. Non quos molestiae ad cumque illum sit fugit  ut consequatur soluta.",
    )
}